# Generated by Django 4.2.7 on 2023-11-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="staff_master_view",
            fields=[
                ("STAFF_ID", models.AutoField(primary_key=True, serialize=False)),
                ("STAFF_NAME", models.CharField(max_length=255)),
                (
                    "USERNAME",
                    models.CharField(
                        default="<django.db.models.fields.AutoField>", max_length=100
                    ),
                ),
                ("GENDER", models.CharField(max_length=1)),
                ("DOB", models.DateField()),
                ("MOBILE_NO", models.CharField(max_length=20)),
                ("EMAIL_ID", models.CharField(db_column="EMAIL_ID", max_length=20)),
                ("JOINING_DATE", models.DateField()),
                ("LEAVING_DATE", models.DateField()),
                ("ACTIVE_STATUS", models.CharField(default="A", max_length=1)),
                ("EMPLOYEE_ID", models.CharField(max_length=20)),
                ("PASSWORD", models.CharField(db_column="PASSWORD", max_length=20)),
                ("STAFF_ROLE_ID", models.IntegerField()),
                ("ROLE_NAME", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "staff_master_view",
                "managed": False,
            },
        ),
    ]
