# Generated by Django 4.2.6 on 2023-10-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff_master_view",
            options={"managed": False},
        ),
    ]
