# Generated by Django 4.2.6 on 2023-10-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_staff_master_view_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_master",
            name="STAFF_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
