# Generated by Django 4.2.6 on 2023-10-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_staff_master_staff_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emergency_contacts",
            old_name="e_id",
            new_name="e",
        ),
    ]
