# Generated by Django 4.2.6 on 2023-10-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_e_id_emergency_contacts_e"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergency_contacts",
            name="e",
            field=models.AutoField(db_column="e_id", primary_key=True, serialize=False),
        ),
    ]
