# Generated by Django 4.2.6 on 2023-10-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_emergency_contacts_e"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emergency_contacts",
            old_name="e",
            new_name="e_id",
        ),
    ]
