# Generated by Django 4.2.6 on 2023-10-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_rename_e_emergency_contacts_e_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident_types",
            old_name="INC_TYPE",
            new_name="INC_TYPE_ID",
        ),
    ]
