# Generated by Django 4.2.6 on 2023-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_rename_inc_type_incident_types_inc_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="cctv",
            fields=[
                ("CCTV_ID", models.AutoField(primary_key=True, serialize=False)),
                ("CCTV_LOCATION", models.CharField(max_length=50)),
                ("MODEL", models.CharField(max_length=50)),
                ("FOLDER", models.CharField(max_length=50)),
            ],
        ),
    ]
